sudo: required
language: java
install: true
script: mvn clean package install -DskipTests=true
services:
  - docker
after_deploy:
  - echo "done deploying"
  
after_success:
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region us-west-2
  - eval $(aws ecr get-login --region us-west-2) 
  - docker build -t awselasticbean .
  - docker tag awselasticbean:latest 574137776403.dkr.ecr.us-west-2.amazonaws.com/shrigowri:latest
  - docker push 574137776403.dkr.ecr.us-west-2.amazonaws.com/shrigowri:latest
